repos:
  - repo: local
    hooks:
      - id: lint 
        name: lint
        stages: [commit]
        language: system
        entry: make lint
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy src/ tests/
        types: [python]
        pass_filenames: false

      - id: test
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest
        types: [python]

      - id: test-cov
        name: pytest-cov
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-report term --cov-report html:./coverage --cov-fail-under=0
        types: [python]
        pass_filenames: false