#!/usr/bin/env python3

from gutscli.exceptions import GutsException
import click
import sys

@click.group()
def cli():
    pass

if __name__ == '__main__':
    try:
        raise GutsException("error")
    except GutsException as e:
        click.secho(str(e), fg='red')
        sys.exit(1)
