#!/usr/bin/env python3

import click
import sys

@click.group()
def cli():
    pass

if __name__ == '__main__':
    try:
        raise Exception("error")
    except Exception as e:
        click.secho(str(e), fg='red')
        sys.exit(1)
